# Generated by Django 3.2.16 on 2023-01-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrption',
            new_name='description',
        ),
    ]
